### ISSUE TITLE
Powershell script unsigned error indicated when attempting to start Julia via Atom

### ISSUE THREAD

**Issue by kkruups** [JunoLab/atom-julia-client#194] opened 2016-07-20 06:17 UTC
**Problem:**  Cannot start Julia Client following error indicated

**Error Message**
C:\mypath\.atom\packages\julia-client\script\spawnInterruptible.ps1 cannot be loaded. The file 
C:\mypath\.atom\packages\julia-client\script\spawnInterruptible.ps1 is not digitally signed. The script will not execute on the system. For more information, see 
about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess

**How do I resolve this Issue?**
**Why isn't the ps script signed?**

**Additional Details**
However opening Julia terminal from Atom menu option works fine.

**Environment Info**
Julia-Client v 0.4.7
Language-Julia v 0.6.0
Julia v 0.4.6
Atom v 1.8.0
Windows 7 - 64bit version

**Comment by pfitzseb** [comment] 2016-07-21 13:55
Sorry, I can't really look into this for the next week or so -- after that I might be able to help you. 

Maybe someone else can help you though...

**Comment by kkruups** [comment] 2016-07-22 06:00
Thanks for the acknowledgement. Hopefully someone else can provide assistance.

BR/kk

**Comment by MikeInnes** [comment] 2016-07-27 18:08
xref to discuss.juno: http://discuss.junolab.org/t/powershell-script-unsigned-error-indicated-when-attempting-to-start-julia-via-atom/758

In general it's best to ask questions in one place, since it's the same people looking at them anyway.

**Comment by pfitzseb** [comment] 2016-08-22 16:39
Is there anything unusual about your setup, @kkruups? We are setting the correct ExecutionPolicy on our call to powershell, so this issue *should* definitely not happen. I also wasn't able to reproduce this on any of the machines I have access to, so I'm afraid I can't really help you without additional information.

What you could try is navigating to `C:\Users\you\.atom\packages\julia-client\script`, open the command line there and type in `powershell .\spawnInterruptible.ps1 123 "test" ["test", "test"]`. If you get the same error as above (note that you'll get an error no matter what, but it should be an `InvalidOperation` error), try `powershell .\spawnInterruptible.ps1 -ExecutionPolicy bypass 123 "test" ["test", "test"]`.
Finally, you could try opening powershell and type in `Get-ExecutionPolicy` -- maybe that'll help.

**Comment by pfitzseb** [comment] 2017-07-02 17:22
Alright, I'll close this for now since there hasn't been an update for ~1 year.

**Closed by pfitzseb** 2017-07-02 17:22 UTC

**Comment by metanoid** [comment] 2018-02-26 07:39
FWIW, I'm also having this issue.
Company policy prevents my from changing the ExecutionPolicy from AllSigned

A workaround I've found is to set "Enable Powershell wrapper" to false in Atom -> Julia -> Settings.
This has the drawback that you can't interrupt the process.
If anyone has a better idea, please let me know.

**Comment by pfitzseb** [comment] 2018-02-26 10:25
I don't think there's a better way then. Do note that you can still interrupt code in the REPL without the powershell wrapper.
