### ISSUE TITLE
Syntax highlighting problem with triple-quotes

### ISSUE THREAD

**Issue by Wajihulhassan** [JunoLab/atom-julia-client#190] opened 2016-06-28 22:14 UTC
I am using Juno on Ubuntu 16.04 and I use triple quotes for documentation in my project. But it seems Juno does not handle syntax highlighting when opening `"""` is followed by newline as shown in the following figure.
![screenshot from 2016-06-28 08-08-22](https://cloud.githubusercontent.com/assets/4715082/16434068/6424bc4e-3d42-11e6-9545-4618ae86358b.png)

while when line start right after opening `"""` it looks fine
![screenshot from 2016-06-28 08-10-21](https://cloud.githubusercontent.com/assets/4715082/16434137/b685a674-3d42-11e6-9afa-d8543c6049ce.png)

Is there any solution to this problem or it is an intended behavior.

**Comment by pfitzseb** [comment] 2016-07-01 09:04
![triple](https://cloud.githubusercontent.com/assets/6735977/16517025/97d4faf0-3f7b-11e6-8215-2aa43500765d.PNG)
I can't reproduce this. Is your version of `language-julia` up to date?

**Comment by Wajihulhassan** [comment] 2016-07-08 00:08
@pfitzseb The problem is `_` (underscore). If you put underscore then you will be able to reproduce the error.

**Comment by pfitzseb** [comment] 2016-07-08 06:44
Oh, I see. This is because `_` starts an italic scope in Markdown, i.e. `_italic_` -> _italic_.
You can just put the `_a` in a code block using backticks:
```
`_a`
```
![highlighting](https://cloud.githubusercontent.com/assets/6735977/16679460/0f295530-44e8-11e6-93f1-567460b28263.PNG)

Also related: https://github.com/JuliaLang/atom-language-julia/issues/33

**Comment by pfitzseb** [comment] 2016-08-22 16:14
I'll close this is in favour of the issue over at atom-language-julia.

**Closed by pfitzseb** 2016-08-22 16:14 UTC

**Comment by dpo** [comment] 2016-09-28 22:44
I'm having the same issue. Although there's an underscore in my docstring, it doesn't seem to be the source of the problem:

![screen shot 2016-09-28 at 18 41 59](https://cloud.githubusercontent.com/assets/38760/18935034/54fc4550-85ab-11e6-89be-4cb96d720791.png)

![screen shot 2016-09-28 at 18 41 44](https://cloud.githubusercontent.com/assets/38760/18935039/5bf3ef0c-85ab-11e6-8d96-3a7d4322fd71.png)

Removing the underscore doesn't change anything. Atom 1.10.2 with all packages updated a few minutes ago.

**Comment by pfitzseb** [comment] 2016-09-29 09:56
That's a different problem though (or rather not a problem at all, probably). The scope at the cursor in the first picture is `string.docstring.julia`, while it's `string.quoted.triple.double.julia` -- the difference in highlighting is probably due to your syntax theme highlighting `docstring` differently than `string`. 
Which syntax theme are you using?

**Comment by dpo** [comment] 2016-09-29 11:55
I use Solarized Dark.

**Comment by pfitzseb** [comment] 2016-09-29 15:24
Yeah, solarized dark doesn't support highlighting `.string` without it also being `.quoted`. Maybe open an issue over at [atom-language-julia](https://github.com/JuliaEditorSupport/atom-language-julia) regarding that, or at the solarized dark repo to add a language specific stylesheet.

**Comment by dpo** [comment] 2016-10-04 23:14
Thanks. Open issue: https://github.com/atom/solarized-dark-syntax/issues/74.
