### ISSUE TITLE
Console Does not respond, no error message given

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/atom-julia-client#126] opened 2016-03-07 13:32 UTC
The Julia console won't respond when I try to type a command.  Evaluating in a window also doesn't work: I get an endless spinning square.  No error message or other outputs are telling me what's going on.

I'm on master for julia-client, ink, Atom.jl and CodeTools.jl

**Comment by MikeInnes** [comment] 2016-03-07 15:50
Did things work previously and then stop? Would be good to see devtools output, I think it's `C-Alt-I` to open the console and then try starting a julia client again.

**Comment by dlfivefifty** [comment] 2016-03-07 20:54
Yes things used to work.  Here’s the console, which shows an error:

Window load time: 909ms
/Users/solver/Projects/julia-client/lib/connection/client.coffee:81 Uncaught (in promise) TypeError: Cannot read property 'working' of undefined(…)
fs.js:854 Uncaught (in promise) Error: ENOENT: no such file or directory, stat 'atom://config'(…)
/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:957 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

**Comment by dlfivefifty** [comment] 2016-03-07 20:58
Hmm, opening a new Atom window fixed the issue.

**Comment by pfitzseb** [comment] 2016-03-08 19:13
Strange. Ima close this, but if you can reproduce it feel free to reopen!

**Closed by pfitzseb** 2016-03-08 19:13 UTC

**Comment by rdeits** [comment] 2016-03-10 19:37
I had this as well upon first installing Atom and Juno on Ubuntu 14.04. It's actually related to the issue mentioned here: https://github.com/moxley/atom-ruby-test/issues/61

When I first started Atom, it had the `config` folder listed in the current project. Right-clicking on that folder and choosing "Remove Project Folder" fixed the issue. It looks like Atom must default to a project that contains the config folder when first opened, so this may end up affecting a lot of new users.

**Comment by dlfivefifty** [comment] 2016-03-10 20:22
Yes, that's exactly what happened with me: there was a configure folder

**Comment by pfitzseb** [comment] 2016-03-10 21:16
Thanks for digging that up, @rdeits! Should be fixed now, I think.

**Comment by rdeits** [comment] 2016-03-10 21:32
Okay, great, thanks!

**Comment by fbanez** [comment] 2016-03-13 03:55
This is happening to me. But I was not able to solve the problem...
I am trying to do what you said, I does not seem to work
