### ISSUE TITLE
Uncaught TypeError: Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by abhijithch** [JunoLab/atom-julia-client#216] opened 2016-08-23 07:02 UTC
[To reproduce:]
1. Install Atom for mac.
2. Within Atom install the package, julia-client.
3. Link to the relevant `julia` binary.
4. Try out any `julia` operation. 

**Atom Version**: 1.9.9
**System**: Mac OS X 10.11.6
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package, v0.5.0
### Stack Trace

Uncaught TypeError: Cannot read property 'open' of undefined

```
At /Users/abhijith/.atom/packages/julia-client/lib/runtime/console.coffee:68

TypeError: Cannot read property 'open' of undefined
    at Object.module.exports.open (/Users/abhijith/.atom/packages/julia-client/lib/runtime/console.coffee:68:7)
    at /Users/abhijith/.atom/packages/julia-client/lib/package/commands.coffee:66:72
    at Object.module.exports.withInk (/Users/abhijith/.atom/packages/julia-client/lib/package/commands.coffee:100:7)
    at atom-workspace.subs.add.atom.commands.add.julia-client:open-console (/Users/abhijith/.atom/packages/julia-client/lib/package/commands.coffee:66:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/abhijith/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Users/abhijith/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/abhijith/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Users/abhijith/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1104:28)
    at EventEmitter.outerCallback (/Users/abhijith/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```
### Commands

```
  3x -7:24.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:02.7.0 core:cancel (a.stack-toggle)
     -3:03.4.0 julia-client:settings (div.panels-item)
     -2:52.7.0 core:backspace (atom-text-editor#julia-client.juliaPath.editor.mini.is-focused)
  2x -2:51.5.0 core:move-right (atom-text-editor#julia-client.juliaPath.editor.mini.is-focused)
  2x -2:46.4.0 core:backspace (atom-text-editor#julia-client.juliaPath.editor.mini.is-focused)
 33x -2:44.1.0 core:move-right (atom-text-editor#julia-client.juliaPath.editor.mini.is-focused)
     -2:16.8.0 julia-client:start-julia (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:05.7.0 editor:newline-below (atom-text-editor.editor.is-focused)
     -1:51 core:save-as (atom-text-editor.editor.is-focused)
     -1:19.4.0 julia-debug:step-into-function (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
     -1:13.8.0 julia-client:run-file (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
     -1:12 julia-client:run-and-move (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
  2x -1:08.1.0 julia-client:open-console (atom-text-editor.editor)
     -0:25 julia-client:open-a-repl (atom-text-editor.editor.is-focused)
     -0:00.0 julia-client:open-console (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "julia-client": {
    "enableMenu": true,
    "enableToolBar": true,
    "juliaPath": "/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia",
    "launchOnStartup": true
  }
}
```
### Installed Packages

``` coffee
# User
ink, v0.5.0 (active)
julia-client, v0.5.0 (active)
language-julia, v0.6.0 (active)
latex-completions, v0.3.1 (active)
tool-bar, v1.0.1 (active)
uber-juno, v0.1.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by pfitzseb** [comment] 2016-08-24 10:08
Can you reproduce this error after restarting Atom?

**Comment by alphaville** [comment] 2016-09-23 13:00
@pfitzseb I ran into the same error. After restarting atom it was automatically resolved.

**Comment by ihnorton** [comment] 2016-12-01 01:27
Possibly caused by out-of-date Ink package. Went away after updating that and restarting (restarting alone did not help).

**Comment by pfitzseb** [comment] 2016-12-04 11:58
Alright, the new Atom version introduced a new update system which should in theory get rid of these kinds of errors if you keep ink and julia-client in sync. I'll close this for now, but feel free to reopen.

**Closed by pfitzseb** 2016-12-04 11:58 UTC

**Comment by Bernalms** [comment] 2017-03-17 00:47
I show the same error even after following all steps in troubleshoot tickets. 
![atom_error_julia_client](https://cloud.githubusercontent.com/assets/7440762/24024429/fb00f354-0a78-11e7-974c-eb5b03b926b6.png)

**Comment by Bernalms** [comment] 2017-03-17 00:47
Any idea??
