### ISSUE TITLE
ArgumentError: premature end of integer: ""

### ISSUE THREAD

**Issue by nilshg** [JunoLab/atom-julia-client#30] opened 2015-09-15 16:56 UTC
Is anyone else seeing this? I'm getting quite a few of these lately, can't really figure out what actions are causing them though:

````
ArgumentError: premature end of integer: ""
 in yieldto at task.jl:76
 in wait at task.jl:372
 in wait at task.jl:287
 in wait at task.jl:113
 [inlined code] from C:\Users\tew207\.julia\v0.4\Lazy\src\dynamic.jl:69
 in anonymous at C:\Users\tew207\.julia\v0.4\Atom\src\eval.jl:44
 in handlemsg at C:\Users\tew207\.julia\v0.4\Atom\src\comm.jl:63
 [inlined code] from C:\Users\tew207\.julia\v0.4\Atom\src\comm.jl:18
 in anonymous at task.jl:68
````

**Comment by nilshg** [comment] 2015-09-15 16:58
Sorry, actually I think I can figure it out: error messages are not being displayed correctly. I can generate the error - ironically - by producing an error; `throw(ErrorException())` will do the trick.

**Comment by Varanas** [comment] 2015-09-15 18:09
Yup, I can reproduce this. And I'm pretty sure this is a regression in `Atom.jl`, since I didn't get that error earlier today before `Pkg.update()`ing.

**Comment by nilshg** [comment] 2015-09-15 18:17
Is there a way around this? Given that I'm not seeing any error messages anymore, debugging is close to impossible with this...

**Comment by Varanas** [comment] 2015-09-15 18:18
Looking into it right now, but I'm getting a) a different backtrace than you and b) neither makes much sense to me.

**Comment by Varanas** [comment] 2015-09-15 19:20
Quick fix: Get rid of [this](https://github.com/JunoLab/Atom.jl/blob/master/src/display/errors.jl#L39) line and you'll get your errors back ;)

**Comment by one-more-minute** [comment] 2015-09-15 19:26
Looks like the highlight function is behaving weirdly on windows, then. Any chance either of you would be able to debug that? Otherwise you won't get the fancy new error highlighting when it works ;)

**Comment by Varanas** [comment] 2015-09-15 19:32
Yeah, sure. Unsurprisingly enough it is the `splitlink` function... I'll try fixing it.

**Comment by Varanas** [comment] 2015-09-15 20:12
Why does a commit to another branch close this issue here? Strange...

**Comment by nilshg** [comment] 2015-09-16 07:54
@Varanas I can't seem to get the errors back by commenting out the line - doing either that or using the version of `errors.jl` in your commit will just get rid of error display altogether, i.e. no ArgumentError in Atom, but also no inline display of errors (the only way to tell that an error occured is that there's no tick displayed after the line was evaluated).

**Comment by Varanas** [comment] 2015-09-16 08:52
Mh. Are you on `atom-julia-client` master? You could also try evaluation the whole file, that should give errors anyways (and was never broken).
I'm not getting any errors in the console, but inline it totally works.

**Comment by nilshg** [comment] 2015-09-16 09:06
Yes, I haven't touched the `atom-julia-client` plugin, and I can reproduce this on my other machine - commenting out the last line in `errors.jl` (and moving the last closing bracket one line up obviously) just gets rid of all error displays.

**Comment by Varanas** [comment] 2015-09-16 09:10
Okay, I think you need at least [this](https://github.com/JunoLab/atom-julia-client/commit/f98dfaec2edb17a2ddf1a944d5e523d23936a8d4) commit for the new errors to work, so try updating `atom-julia-client` (didn't break anything for me, for what it's worth).

**Comment by nilshg** [comment] 2015-09-16 09:15
Hmm... when replacing the `eval.coffee` with the changes in that commit, I'm just making things worse... Now getting: 

````
TypeError: Cannot read property 'linkify' of undefined
    at Object.<anonymous> (C:\Users\tew207\.atom\packages\julia-client\lib\eval.coffee:31:19)
    at Object.module.exports.input (C:\Users\tew207\.atom\packages\julia-client\lib\connection\client.coffee:26:38)
    at C:\Users\tew207\.atom\packages\julia-client\lib\connection\tcp.coffee:60:27
    at Socket.<anonymous> (C:\Users\tew207\.atom\packages\julia-client\lib\connection\tcp.coffee:23:25)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:109:10)
    at TCP.onread (net.js:517:20)
````

**Comment by Varanas** [comment] 2015-09-16 09:25
Uhoh... since you're getting an `ink`-error, you might as well try updating that to master too. And I'm not sure if exchanging `eval.coffee` is enough - that depends on where you which commit you were on before.

**Comment by nilshg** [comment] 2015-09-16 09:37
Okay, I've uninstalled everything and reinstalled via the dev-install instructions (forked and cloned the `atom-julia-client` and `atom-ink` repos and installed via apm command line, checked out `Atom.jl` and `CodeTools.jl`). 

I can now report that I successfully made it back to the original error :) (that is, `ArgumentError: premature end of integer ""` when an error should be displayed)

**Comment by Varanas** [comment] 2015-09-16 09:39
Congratulations :)
Now you should get the actual errors displayed with commenting out the `highlights`-line in `Atom.jl`. It doesn't do anything yet anyways and I guess it'll take a while till I get it fixed for all cases in a remotely nice way.

**Comment by nilshg** [comment] 2015-09-16 09:42
Yay, it works! Thanks a lot, this was a huge productivity killer...

**Comment by Varanas** [comment] 2015-09-16 19:57
Should be fixed with https://github.com/JunoLab/Atom.jl/commit/2fbac8dfc19ce08e66eaaaaf85731da5a4851a38.

**Closed by Varanas** 2015-09-16 19:57 UTC
Labels: bug
