### ISSUE TITLE
Default console show method

### ISSUE THREAD

**Issue by jebej** [JunoLab/atom-julia-client#342] opened 2017-05-10 18:38 UTC
It seems the the default `show` method used to display console output has changed a while ago. Now, the compact format `show` is used. This is not ideal, as it differs from the standard julia console print (which shows the `::MIME"text/plain"` by default). This is annoying, in particular with `@benchmark` as the full output is inaccessible.

**Comment by pfitzseb** [comment] 2017-05-10 19:41
I vaguely remember there being some reason for using the two-argument `show`, but not what it was. As such, I'd be fine with changing this default.

That said, I can't reproduce this with regard to `@benchmark`:
![res](https://cloud.githubusercontent.com/assets/6735977/25917748/6d9d6674-35c9-11e7-9cbc-1453242b5d56.PNG)

**Comment by jebej** [comment] 2017-05-10 19:58
Hmmm I only get the `Trial(...)` text, both when ctrl-enter evaluating a line and in the console.

**Comment by pfitzseb** [comment] 2017-05-18 21:28
Just had a look again -- on master we use `show(IOContext(io, limit = true), MIME"text/plain"(), x)` since https://github.com/JunoLab/Juno.jl/commit/15f540154aa04e422974f18e0072417b725ef367. Therefore this will be fixed with the next release of Juno. :)

**Closed by pfitzseb** 2017-05-18 21:28 UTC
