### ISSUE TITLE
Atom unable to find Julia binary

### ISSUE THREAD

**Issue by Sam-Huntington** [JunoLab/atom-julia-client#98] opened 2016-02-02 17:15 UTC
I'm able to start up Atom, but when i try to evaluate a line of code i get the following error:

'C:/Users/huntington/AppData/Local/Julia-0.4.3/bin/julia.exe' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

I've tried switching from forward slashes to backslashes and even double backslashes but nothing seems to work. I double checked the location and Julia.exe is indeed at that path. 
Please help!

**Comment by KristofferC** [comment] 2016-02-02 17:29
I have the same and julia is indeed in my path. Ubuntu here.

**Comment by Varanas** [comment] 2016-02-02 22:18
@Sam-Huntington Could you try activating the `Enable Powershell Wrapper` option in `julia-client`s settings? 

Also, you might try [this](https://github.com/JunoLab/atom-julia-client/issues/88#issuecomment-172093069) again.

**Comment by Varanas** [comment] 2016-02-03 10:26
Does [this](https://github.com/JunoLab/atom-julia-client/issues/97#issuecomment-178891604) solve the problem?

**Comment by Sam-Huntington** [comment] 2016-02-03 15:08
I've rebuilt both Julia and Atom, and reinstalled all packages. I have `Enable Powershell Wrapper` on, as well as `Launch on Startup`.
Now i get the following error whenever i even click or scroll through my code:

warning: atom.jl: unrecognized message Dict{abstractString,Any}{"callback"=>1,"type"=>"module).

**Comment by one-more-minute** [comment] 2016-02-03 15:12
Looks like an outdated Atom.jl to me, try `Pkg.update()` from the repl.

**Comment by Sam-Huntington** [comment] 2016-02-03 15:52
Can't believe i missed that. Works now -- thanks again!

**Comment by KristofferC** [comment] 2016-02-03 15:59
Think that was my problem as well.

**Comment by grahamfindlay** [comment] 2016-02-12 02:29
I am having this issue as well, except a simple `Pkg.update` did not work for me. My environment:

* Ubuntu 14.04
* Julia 0.4.4, built from source
* Atom 1.5.2, from official .deb
* Julia `Atom` package 0.3.0
* Atom `language-julia` package 0.5.0
* Atom `ink` package 0.3.2
* Atom `julia-client` package 0.3.1

Julia is indeed in my path. Yet I am unable to spawn when pointing `julia-client` to 'julia', the actual binary itself at '/path/to/source/julia/usr/bin/julia', or anywhere it is symlinked from (e.g. '/usr/bin/julia').

**Comment by 34383c** [comment] 2016-02-14 19:55
@KristofferC and @grahamfindlay,
I was able to fix the `WARNING: Atom.jl: unrecognised message ping` problem (and other warnings and errors) by updating `Atom.jl`, `CodeTools.jl`, and `JuliaParser.jl` via
```julia
Pkg.checkout("CodeTools")
Pkg.checkout("JuliaParser")
Pkg.checkout("Atom")
```
You can enter these commands either in the REPL or in Atom, whichever you prefer.

**Comment by grahamfindlay** [comment] 2016-02-15 16:15
Didn't resolve the issue for me, unfortunately. No packages needed updating, leaving me still at:

* CodeTools.jl 0.2.0
* JuliaParser.jl 0.6.4
* Atom.jl 0.3.0

**Comment by 34383c** [comment] 2016-02-15 18:44
Hey @grahamfindlay 

Hm, same versions as my Julia packages.
Which is a bit strange, because it seems likely that the problem is a version mismatch between `Atom.jl` and `julia-client`. This is the `Atom.jl` commit that introduced the `ping` handler: https://github.com/JunoLab/Atom.jl/commit/f8c10a39b3b0e57fc8cbbe3f4910a04611f922f6. And this is the `julia-client` commit that introduced calls to `ping`: https://github.com/JunoLab/atom-julia-client/commit/57ebc59f5604dfad1b89f8ba55e518298d7b6bf4.

(Btw, in my experience, you need to restart Atom for any changes made to Julia's packages to become active in Atom.)

What about your `julia-client`? Mine is version 0.3.1.
If you haven't updated your `julia-client` in the past two weeks, try doing:
```
cd /path/to/julia-client
git pull
```
(And restart Atom, if it was running.)

**Comment by grahamfindlay** [comment] 2016-02-15 19:19
Ah, I think I was unclear earlier. My apologies.
The issue that I am experiencing is the one for which this ticket was originally opened, namely: *'/usr/bin/julia' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.* You mentioned that updating packages fixed the *unrecognised message ping* issue, but also others, which I hoped might include mine.

**Comment by 34383c** [comment] 2016-02-15 20:31
Are you perhaps using OS X and launching Atom through the GUI?
Do you get the same error if you start Atom through the console?

If the answer to both of these questions is no, can you please look in (or even better post the contents of) the developer console of Atom, which can be accessed by clicking on the "View" option at the menu bar at the top of Atom, then choosing "Developer"->"Toggle Developer Tools", and then in the newly opened Developer Tools view, click on the "»" at the top and chose "Console".

**Comment by Varanas** [comment] 2016-02-15 20:46
Dev console output would certainly be useful, if there is any.

Starting from the console should help when you want to spawn Julia via something in your `PATH`, but not if you specify a complete path.

Also, it is very strange that you're getting the standard Atom error when trying to start Julia, since that means our own checks have determined that the path at least exists...

**Comment by grahamfindlay** [comment] 2016-02-15 21:26
@34383c 
Nope, I'm using Ubuntu 14.04, and the issue happens regardless of whether I launch through a GUI or a console. 

@Varanas 
Here's the dev console output. Sorry I didn't include it straightaway. FYI, It's the same regardless of where I start Atom from. 
```
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
Uncaught Error: spawn /usr/bin/julia ENOENT
```
Thanks for helping.

**Comment by Varanas** [comment] 2016-02-15 22:04
Could you try 
```js
cp = require('child_process')
cp.spawn('/usr/bin/julia')
```
in the dev console? If this gives `Uncaught Error: spawn /usr/bin/julia ENOENT` as well, then could you try
```js
fs = require('fs')
fs.existsSync('/usr/bin/julia')
```
just to check whether Atom finds that path?

**Comment by grahamfindlay** [comment] 2016-02-15 23:40
No errors thrown when spawning manually from the console. 

I noticed that with the dev console open *before* trying to launch Julia from `julia-client`, the uncaught error that I was referring to earlier can be explored in more detail. Here's the trace:
```
exports._errnoException	@	util.js:837
ChildProcess._handle.onexit	@	internal/child_process.js:178
onErrorNT	@	internal/child_process.js:344
doNTCallback2	@	node.js:441
_tickCallback	@	node.js:355
```
Dropping a breakpoint at `node.js:355` reveals that the child process that is trying to spawn has args `/usr/bin/julia /home/graham/.atom/packages/julia-client/script/boot.jl 41830`. Executing this in a terminal triggers a series of `Recompiling stale cache files for module X` messages when `boot.jl` tries to `include('caches.jl')`. Then a connection to Atom is successfully established on port 41830. At this point, you can unpause execution in the Atom debugger, and `julia-client` connects successfully, and evaluates expressions within Atom as intended.

**Comment by Varanas** [comment] 2016-02-29 15:48
@grahamfindlay Sorry for the delay, but does spawning Julia work now that no more recompilation is necessary?

**Comment by grahamfindlay** [comment] 2016-03-01 02:15
@Varanas
Yep! And I just set up `julia-client` on a coworker's machine (same environment as I had), but this time forced the recompilation with a `using Atom` call, and he had no problems.

**Comment by Varanas** [comment] 2016-03-01 08:59
Sweet! I'll close this then.

There's also  a newish note in the manual about doing `using Atom` at the REPL before firing up Atom, so this may be enough for future reference.

**Closed by Varanas** 2016-03-01 08:59 UTC
Labels: bug
