### ISSUE TITLE
Can't find Julia

### ISSUE THREAD

**Issue by jpiccoli** [JunoLab/atom-julia-client#120] opened 2016-02-29 01:08 UTC
I keep getting the message "Julia was not found - We tried to launch Julia from ..." after selecting "Start Julia" from Atom 1.5.3. I tried the following settings for the Julia path in the julia-client path in Atom (my installation is at C:\Julia-0.4.3\bin):
1. C:\Julia-0.4.3\bin
2. C:\Julia-0.4.3\bin\julia.exe

I'm running Windows 8.1 with Julia 0.43. I can run Julia both from the desktop icon and from a command prompt. My $PATH contains item #1 above. I was using the directions from the following:

https://github.com/JunoLab/atom-julia-client/tree/master/manual

Let me know if I can provide any more info. Thanks!

**Comment by Varanas** [comment] 2016-02-29 12:04
You should be able to launch Julia with the default setting for the path, `julia`, since it's on the PATH environment variable. The second option should work also. Are you on the latest versions of `atom-julia-client` and `atom-ink`?

Just to be sure: The "..." in the error message is a substitute for your `Julia Path` setting, correct?

**Comment by jpiccoli** [comment] 2016-03-01 03:00
Hello Sebastian,

According to Atom I am update to date with all my installed packages (I
determined this after selecting "Check For Updates" in the Atom "Update"
item; ink 0.4.0 and julia-client 0.4.0). I am attaching screenshots of the
errors I am getting. One other point: I saw the errors when selecting
"Start Julia" from the Julia drop-down menu in Atom. I also saw the exact
same errors after selecting the "Open Console" item from the drop-down.

Thanks,
Joseph A. Piccoli

On Mon, Feb 29, 2016 at 4:04 AM, Sebastian <notifications@github.com> wrote:

> You should be able to launch Julia with the default setting for the path,
> julia, since it's on the PATH environment variable. The second option
> should work also. Are you on the latest versions of atom-julia-client and
> atom-ink?
>
> Just to be sure: The "..." in the error message is a substitute for your Julia
> Path setting, correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JunoLab/atom-julia-client/issues/120#issuecomment-190185161>
> .
>



-- 
Joseph A. Piccoli
joep13676@gmail.com
(971) 533-6815

**Comment by pfitzseb** [comment] 2016-03-10 21:27
Could you try the [dev install instructions](https://github.com/JunoLab/atom-julia-client/tree/master/docs) to get on `julia-client` master? Hopefully, this has been fixed in the last couple of days, so it'd be great to know if we still have some work to do regarding this before releasing a new version.
Thanks!

**Comment by jpiccoli** [comment] 2016-03-12 23:07
Sebastian,

I followed the directions and I still am getting a message from Atom saying
it can't find Julia. I don't know much about this but I think you've got a
serious problem with Atom somewhere. I understand you're in the development
stages but this product is not usable in its present form if the IDE can't
find the compiler/interpreter. Let me know if there's anything else you
want me to try.

Joe Piccoli

On Thu, Mar 10, 2016 at 1:27 PM, Sebastian Pfitzner <
notifications@github.com> wrote:

> Could you try the dev install instructions
> <https://github.com/JunoLab/atom-julia-client/tree/master/docs> to get on
> julia-client master? Hopefully, this has been fixed in the last couple of
> days, so it'd be great to know if we still have some work to do regarding
> this before releasing a new version.
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JunoLab/atom-julia-client/issues/120#issuecomment-195056968>
> .
>



-- 
Joseph A. Piccoli
joep13676@gmail.com
(971) 533-6815

**Comment by mandarup** [comment] 2016-04-13 20:56
I get similar error:
`julia' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.`

I have updated `atom-julia-client` and `atom-in` and correct path to julia


`
Window load time: 1077ms
/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:982 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:982 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/Users/mupadhye/.atom/packages/julia-client/lib/connection/client.coffee:81 Uncaught (in promise) TypeError: Cannot read property 'working' of undefined(…)
events.js:141 Uncaught Error: spawn julia ENOENT
`

**Comment by pfitzseb** [comment] 2016-04-14 13:46
@mandarup What is the path you have in the settings? Just `julia` and you have the binary on your `PATH`, or the full path? If the former, you may need to start Atom from the command line to get the environment variable properly imported -- not sure though, I don't have any experience with OSX.

**Comment by mandarup** [comment] 2016-04-14 21:02
@pfitzseb  i have set full path in julia-client settings:
/Applications/Julia-0.4.5.app/Contents/Resources/julia/bin/julia

**Comment by liusihaoshiwo** [comment] 2016-06-10 04:12
I have the same problem on WIn7. I set the path in Atom with this "D:\Program Files\julia-0.4.5\bin\julia.exe". But it just cannot find the julia. I can open julia without using Atom.

**Comment by pfitzseb** [comment] 2016-06-10 07:40
Did you enter the path with quotation marks? If so, try without.

**Comment by liusihaoshiwo** [comment] 2016-06-10 07:44
Actually，I didn't enter path with quotation and it is kind of strange because I installed Atom in another computer which is win10.It can works with julia but win7 failed.I don't know why

**Comment by pfitzseb** [comment] 2016-06-10 09:25
Alright, I'll set up a Win7 VM and try to reproduce this. Just to be sure: Is the `julia-client` package up to date?

**Comment by liusihaoshiwo** [comment] 2016-06-10 09:31
yes，I have checked it.  It says all package have already been updated. I guess it might be a problem of environment variable, because I installed a lot of softwares. Maybe one of them change it

**Comment by pfitzseb** [comment] 2016-06-10 10:12
Can you check whether you have `%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\` in your `Path`? Could be the problem, because we use powershell for starting Julia.

**Comment by liusihaoshiwo** [comment] 2016-06-10 11:25
I have met that problem too, but I have already fixed it. CANNOT FIND JULIA might be a similiar but diffierent problem :( Anyway, I'm using command console outside Atom, hoping you can fix that problem ASAP

**Comment by pfitzseb** [comment] 2016-06-14 09:27
Sorry, I didn't have any luck reproducing this, neither on a Win 7 VM nor elsewhere.

**Comment by pfitzseb** [comment] 2016-08-22 16:21
I'll close this for now -- if you still get this error, feel free to reopen, @jpiccoli.

**Closed by pfitzseb** 2016-08-22 16:21 UTC
Labels: bug

**Comment by ABMSUH** [comment] 2019-03-29 17:59
Hi,
I am facing a big problem in Julia as follow:

“We tried to lunch Julia from:
C:\Users\Pechman\AppData\Local\Julia-1.1.0\bin\julia.exe
This path can be changed in the settings.
Details:
Access is denied.”

Please advise me to fix it…
