### ISSUE TITLE
Failed to activate the julia-client package

### ISSUE THREAD

**Issue by kkruups** [JunoLab/atom-julia-client#270] opened 2016-10-18 02:25 UTC
## **Environment:**

**OS:** Win 7
**Atom:** 1.11.2
Julia Upgrade from:  0.4.7 to  0.5.9
## Error Indicated via Atom when installing julia-client package:

**Failed to activate the julia-client package**

**Stack Trace**

Autocomplete provider 'Object(undefined)'
specifies `selector` instead of the `scopeSelector` attribute.
See https://github.com/atom/autocomplete-plus/wiki/Provider-API.

Autocomplete provider 'Object(undefined)'
specifies `selector` instead of the `scopeSelector` attribute.
See https://github.com/atom/autocomplete-plus/wiki/Provider-API.

```
Error: Autocomplete provider 'Object(undefined)'
specifies `selector` instead of the `scopeSelector` attribute.
See https://github.com/atom/autocomplete-plus/wiki/Provider-API.
    at ProviderManager.module.exports.ProviderManager.registerProvider (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\autocomplete-plus\lib\provider-manager.js:302:17)
    at ProviderManager.registerProvider (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\autocomplete-plus\lib\provider-manager.js:3:59)
    at C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\autocomplete-plus\lib\main.js:83:65
    at Object.module.exports.requireAutocompleteManagerAsync (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\autocomplete-plus\lib\main.js:23:49)
    at Object.module.exports.consumeProvider (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\autocomplete-plus\lib\main.js:79:12)
    at Object.module.exports.consumeProvider_3_0 (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\autocomplete-plus\lib\main.js:65:19)
    at Provider.module.exports.Provider.provide (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\service-hub\lib\provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.provide (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\service-hub\lib\service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:355:71)
    at Package.module.exports.Package.activateNow (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:186:16)
    at C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:92:15)
    at C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:397:31

```

**Comment by pfitzseb** [comment] 2016-10-18 10:12
Do you still get this after restarting Atom?

**Comment by kkruups** [comment] 2016-10-19 03:32
I don't get same error after re-starting I get a new error:

## New Error

Failed to activate the julia-client package
Cannot read property 'addScope' of undefined

## Stack Trace

TypeError: Cannot read property 'addScope' of undefined
    at Object.module.exports.consumeInk (file:///C:/Users/22711973/.atom/packages/julia-client/lib/runtime/debugger.coffee:78:26)
    at Object.module.exports.consumeInk (file:///C:/Users/22711973/.atom/packages/julia-client/lib/runtime.coffee:21:15)
    at Object.module.exports.JuliaClient.consumeInk (file:///C:/Users/22711973/.atom/packages/julia-client/lib/julia-client.coffee:33:7)
    at Provider.module.exports.Provider.provide (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\service-hub\lib\provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.consume (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\service-hub\lib\service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:363:75)
    at Package.module.exports.Package.activateNow (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:186:16)
    at C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:92:15)
    at C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\22711973\AppData\Local\atom\app-1.11.2\resources\app.asar\src\atom-environment.js:779:28

**Comment by ihnorton** [comment] 2016-12-01 01:27
Possibly caused by out-of-date Ink package. Went away after updating that and restarting (restarting alone did not help).

**Comment by asampal** [comment] 2017-03-14 01:08
I'm getting this with everything Julia-related cleaned out from under Atom directories.

After installing `uber-juno`, I restart Atom and find `uber-juno` is disabled. I enable it and restart again. Various extensions are then installed, but the following failure results at some point.

**Julia**: 0.6.0-pre.alpha
**Atom**: 1.16.0-beta0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.5.12


### Stack Trace

Failed to activate the julia-client package

```
At bar is not defined

ReferenceError: bar is not defined
    at Console.render (console.js:95:5)
    at Object.initialize (/packages/ink/node_modules/etch/dist/component-helpers.js:60:34)
    at Console (console.js:77:10)
    at Function.fromId (pane-item.js:74:36)
    at Object.create (/packages/julia-client/lib/runtime/console.coffee:47:23)
    at Object.activate (/packages/julia-client/lib/runtime/console.coffee:16:6)
    at Object.consumeInk (/packages/julia-client/lib/runtime.coffee:24:11)
    at Object.consumeInk (/packages/julia-client/lib/julia-client.coffee:36:7)
    at Provider.module.exports.Provider.provide (/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.consume (/app.asar/node_modules/service-hub/lib/service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (/app.asar/src/package.js:404:75)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:221:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:265:9)
    at ChildProcess.process.on.code (/app.asar/src/buffered-process.js:295:9)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -2:15.1.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-toolbar 0.1.6 
atom-yeoman 0.3.15 
busy-signal 1.3.0 
dartlang 0.6.45 
go-debug 1.1.0 
go-plus 5.3.2 
go-signature-statusbar 1.2.0 
hyperclick 0.0.40 
ink 0.6.5 
intentions 1.1.2 
ionide-fake 1.2.2 
ionide-fsharp undefined 
ionide-fsi undefined 
ionide-installer 1.4.0 
ionide-paket 2.2.6 
ionide-webview 1.0.3 
ionide-yeoman 2.0.0 
julia-client 0.5.12 
language-elm 1.5.0 
language-julia 0.10.0 
latex-completions 0.3.2 
linter 2.0.0 
linter-elm-make 0.22.5 
linter-ui-default 1.0.0 
lisp-paredit 0.5.5 
minimap 4.26.8 
minimap-hide 0.3.0 
Parinfer 1.17.0 
proto-repl 1.4.17 
proto-repl-charts 0.4.0 
synced-sidebar 0.4.3 
tool-bar 1.1.0 
uber-juno 0.1.1 
```

**Comment by TotalVerb** [comment] 2017-03-18 02:12
@ihnorton's solution of updating ink worked for me.

**Comment by asampal** [comment] 2017-03-18 08:49
@TotalVerb as you can see above, I'm using the latest ink, 0.6.5, so there's nothing to upgrade.

**Comment by davidssmith** [comment] 2017-03-22 19:45
I also have this problem. 
```
ReferenceError: g is not defined
    at BreakpointManager.deinit (breakpoints.js:84:9)
    at subs.add.ed.observeGrammar (breakpoints.js:43:16)
    at TextEditor.module.exports.TextEditor.observeGrammar (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:623:7)
    at BreakpointManager.subs.add.atom.workspace.observeTextEditors.ed (breakpoints.js:39:24)
    at Workspace.observeTextEditors (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/workspace.js:305:53)
    at new BreakpointManager (breakpoints.js:38:34)
    at Object.consumeInk (debugger.js:113:17)
    at Object.consumeInk (/Users/dss/.atom/packages/julia-client/lib/runtime.coffee:21:15)
    at Object.consumeInk (/Users/dss/.atom/packages/julia-client/lib/julia-client.coffee:36:7)
    at Provider.module.exports.Provider.provide (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:404:75)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:221:16)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:96:15)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:550:34)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:508:46)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/atom-environment.js:826:28
```
```
julia> versioninfo()
Julia Version 0.5.1-pre+31
Commit 6a1e339 (2016-11-17 17:50 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin16.3.0)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by nw11** [comment] 2017-04-18 08:01
After updating julia-client package got this:


ink.breakpoints is not a constructor
TypeError: ink.breakpoints is not a constructor
    at Object.consumeInk (/home/nic/.atom/packages/julia-client/lib/runtime/debugger.js:113:17)
    at Object.consumeInk (/home/nic/.atom/packages/julia-client/lib/runtime.coffee:21:15)
    at Object.consumeInk (/home/nic/.atom/packages/julia-client/lib/julia-client.coffee:36:7)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.consume (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app.asar/src/package.js:404:75)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:221:16)
    at /usr/share/atom/resources/app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:96:15)
    at /usr/share/atom/resources/app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:550:34)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:508:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:826:28


julia> versioninfo()
Julia Version 0.5.2-pre+1
Commit a6c55c5* (2017-03-06 03:59 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

**Comment by pfitzseb** [comment] 2017-05-03 13:01
Closing, since this seems to be fixed with latest ink.

**Closed by pfitzseb** 2017-05-03 13:01 UTC

**Comment by huckl3b3rry87** [comment] 2017-06-30 18:56
I am getting this error as well, it says:
```
unmatched OUTDENT in /home/febbo/.atom/packages/julia-client/lib/misc/blocks.coffee:27:62
Hide Stack Trace
SyntaxError: unmatched OUTDENT
  at /home/febbo/.atom/packages/julia-client/lib/misc/blocks.coffee:27:62
```
I am running Ubuntu and it says that all of my packages are up to date

**Comment by pfitzseb** [comment] 2017-06-30 20:47
Hm, are you sure you're on a release version of the Atom packages, not on some branch or something? I can't reproduce that error. The travis failure is because of deprecation warnings on Atom 1.19 (or whatever the current beta version is), not because of invalid syntax.

**Comment by huckl3b3rry87** [comment] 2017-06-30 21:13
No, brand new release versions of everything

**Comment by mbeltagy** [comment] 2018-04-22 12:59
I got this after the latest update. All my packages are up to date, including `ink` etc.. 


**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Ubuntu 14.04.5
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.6.12


### Stack Trace

Failed to activate the julia-client package

```
At Cannot read property 'tags' of undefined

TypeError: Cannot read property 'tags' of undefined
    at /packages/julia-client/lib/runtime/plots.coffee:4:18)
    at /packages/julia-client/lib/runtime/plots.coffee:1:1)
    at /packages/julia-client/lib/runtime/plots.coffee:1:1)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/julia-client/lib/runtime.coffee:8:16)
    at /packages/julia-client/lib/runtime.coffee:1:1)
    at /packages/julia-client/lib/runtime.coffee:1:1)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/julia-client/lib/julia-client.coffee:11:15)
    at /packages/julia-client/lib/julia-client.coffee:1:1)
    at /packages/julia-client/lib/julia-client.coffee:1:1)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
ex-mode 0.18.0 
git-plus 7.10.2 
gpp-compiler 3.0.7 
Hydrogen 2.4.1 
ink 0.8.4 
intentions 1.1.5 
julia-client 0.6.12 
language-julia 0.16.0 
latex-completions 0.3.3 
linter 2.2.0 
linter-ui-default 1.7.1 
split-diff 1.5.2 
vim-mode-plus 1.32.0 
vim-mode-plus-ex-mode 0.11.0 
```

**Comment by mbeltagy** [comment] 2018-04-22 15:08
Deleting my `~/.atom` folder and then installing `uber-juno` fixed the problem. However if I try to install `julia-client` package independently it fails with the same error.

**Comment by mohamed82008** [comment] 2018-08-07 19:57
I am still getting this error btw.
