### ISSUE TITLE
Julia could not be found (julia-client 2.1)

### ISSUE THREAD

**Issue by Sam-Huntington** [JunoLab/atom-julia-client#88] opened 2016-01-15 20:42 UTC
I just installed version 2.1 of julia-client and now atom can't seem to find julia. 
I get the error:
"We tried to launch Julia from:
C:\Users\huntington\AppData\Local\Julia-0.4.3\bin\julia.exe"
Previously i had julia-client v1.3 which had no problem finding julia at the same path

**Comment by Varanas** [comment] 2016-01-15 20:54
Could you try setting the Julia path to `C:/Users/huntington/AppData/Local/Julia-0.4.3/bin/julia.exe`? 

I'll have a look at fixing this in a sane way though...

**Comment by Sam-Huntington** [comment] 2016-01-15 21:04
Thanks for the quick response. I tried what you suggested, as well as
double backslashes and putting quotes around it, but still no luck.
Any other ideas?

**Comment by Varanas** [comment] 2016-01-15 21:09
Huh, strange.

Could you try opening the dev console with `Ctrl-Alt-i` and then typing
```
fs = require('fs')
fs.existsSync('C:/Users/huntington/AppData/Local/Julia-0.4.3/bin/julia.exe')
```
into the console?

I can't reproduce your issue here though.

**Comment by one-more-minute** [comment] 2016-01-15 21:13
@Varanas it looks like the fix you merged earlier [appears in master](https://github.com/JunoLab/atom-julia-client/commits/master) but [not in v0.2.1]. I have no idea why that's happened.

**Comment by Varanas** [comment] 2016-01-15 21:16
Oh, true. Strange... Did you pull before tagging?

**Comment by one-more-minute** [comment] 2016-01-15 21:22
I'm sure I pulled and tested it before tagging so I have no idea what's gone on there. Either way I've gone ahead and re-released a patch, so you should be good to go @Sam-Huntington.

**Closed by one-more-minute** 2016-01-15 21:22 UTC
Labels: bug

**Comment by Sam-Huntington** [comment] 2016-01-15 21:34
It worked! thanks guys

**Comment by ABMSUH** [comment] 2019-03-29 17:59
Hi,
I am facing a big problem in Julia as follow:

“We tried to lunch Julia from:
C:\Users\Pechman\AppData\Local\Julia-1.1.0\bin\julia.exe
This path can be changed in the settings.
Details:
Access is denied.”

Please advise me to fix it…
