### ISSUE TITLE
Troubles upgrading package

### ISSUE THREAD

**Issue by jebej** [JunoLab/atom-julia-client#466] opened 2018-05-14 19:51 UTC
For the last couple releases, I have had issues upgrading the `atom-julia-client` package in Atom. `ink` updates fine, but the client stays in the "updating" state indefinitely, until I close Atom, at which point I have to uninstall and reinstall the package.

I have deleted most of the content of my `.atom` folder, but that didn't seem to fix it. Are there any logs I can check to see what is wrong?

**Comment by pfitzseb** [comment] 2018-05-15 08:55
Yeah, that's rather unfortunate. The problem is that we're holding on to a handle to a binary somewhere, which then can't be updated, which in turn leaves julia-client broken.

One workaround is to disable ink before updating julia-client.

**Comment by pfitzseb** [comment] 2018-05-15 09:29
Also closing in favour of https://github.com/JunoLab/atom-julia-client/issues/457.

**Closed by pfitzseb** 2018-05-15 09:29 UTC
Labels: bug
