### ISSUE TITLE
Goto Symbol not working in console

### ISSUE THREAD

**Issue by malmaud** [JunoLab/atom-julia-client#372] opened 2017-07-25 03:12 UTC
Executing `Julia Client: goto symbol` is having no effect - no dialog appears, and no error message appears anywhere, including the JS console. Let me know what information I can provide that would be helpful.

**Comment by pfitzseb** [comment] 2017-07-26 10:10
I (still) can't reproduce this, so:

- What versions of julia-client and ink are you running? 
- What symbol where you trying the command on? 
- Does `methods(yoursymbol)` work?

**Comment by yha** [comment] 2017-09-04 15:04
I'm not sure if this is the same problem, but I found it works fine in the text editor, but not in the console. When either using "Go to definition" from the context menu" or the built-in shortcut ctrl+j ctrl+g, nothing happens in the console. When using Ctrl+Shift+P from the console and searching for "goto symbol" it doesn't even appear.
I would basically expect all Julia related commands and shortcuts to work the same whether invoked from the editor or console (where it makes sense).

**Comment by pfitzseb** [comment] 2017-09-04 16:31
If you can't find `Goto symbol` in the command pane (while you're in a Julia file) then something is wrong with your install. Are you on up-to-date versions of ink, julia-client and Atom itself?

**Comment by yha** [comment] 2017-09-04 16:57
I _can_ find `Goto symbol` when in a Julia file, just not when in the console.

**Comment by pfitzseb** [comment] 2017-09-04 19:35
Right, didn't read that very carefully. 
I'll take a look at fixing this tomorrow.

**Comment by pfitzseb** [comment] 2018-01-14 20:23
`wontfix` since the old console is deprecated.

**Closed by pfitzseb** 2018-01-14 20:23 UTC
Labels: bug, wontfix
