### ISSUE TITLE
'using Winston' gives TkWidget convert error for any input

### ISSUE THREAD

**Issue by ericbumbalough** [JunoLab/atom-julia-client#135] opened 2016-03-22 23:30 UTC
After 'using Winston' any input gives the error below. This is after Pkg.update(), Pkg.build("Winston"), Pkg.build("Atom") and Pkg.build("Tk"). Everything works fine in IJulia and the REPL. 

![image](https://cloud.githubusercontent.com/assets/15643053/13970075/f3e8ebe4-f05c-11e5-95ff-5478a8f6bf36.png)

> Julia Version 0.4.5
> Commit 2ac304d (2016-03-18 00:58 UTC)
> Platform Info:
>   System: Windows (x86_64-w64-mingw32)
>   CPU: AMD FX(tm)-6100 Six-Core Processor             
>   WORD_SIZE: 64
>            Microsoft Windows [Version 6.1.7601]
>- Winston                       0.11.13+           master
> - Tk                            0.3.7              master

Thanks for any help.

**Comment by pfitzseb** [comment] 2016-03-23 09:05
Duplicate of #118.

**Closed by pfitzseb** 2016-03-23 09:05 UTC
