### ISSUE TITLE
Evalling `@time gc()` after reading a large file results in allocating 12GB of memory and then crashing

### ISSUE THREAD

**Issue by jamii** [JunoLab/atom-julia-client#247] opened 2016-09-29 11:50 UTC
Read a 1GB string and then gc. Works fine in the repl:

``` julia
julia> @time begin 
         s = readstring(open("../imdb/movie_info.csv"))
         nothing
       end
  0.216533 seconds (151 allocations: 919.144 MB, 16.75% gc time)

julia> @time gc()
  0.045423 seconds (648 allocations: 33.249 KB, 92.16% gc time)
```

In atom:

``` julia
module Test

@time begin 
  s = readstring(open("../imdb/movie_info.csv"))
  nothing
end # ctrl-enter here

@time gc() # ctrl-enter here

end
```

The second eval takes about 10s to return, allocates ~12gb of memory and then [crashes julia-client](http://i.imgur.com/jVwG8oZ.png). Atom sometimes becomes unresponsive afterwards, but is not consuming any cpu.

``` julia
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

julia> Pkg.status()
10 required packages:
 - Atom                          0.5.2
 - Benchmark                     0.1.0
 - BenchmarkTools                0.0.5
 - Blink                         0.4.1
 - Gadfly                        0.4.4
 - Hiccup                        0.0.3
 - JLD                           0.6.3
 - Match                         0.3.0
 - PyPlot                        2.2.4
 - SQLite                        0.3.7
80 additional packages:
 - ASTInterpreter                0.0.4
 - AbstractTrees                 0.0.4
 - ArgParse                      0.3.1
 - AxisAlgorithms                0.1.5
 - BinDeps                       0.4.5
 - Blosc                         0.1.7
 - COFF                          0.0.2
 - CRC                           1.1.1
 - Calculus                      0.1.15
 - CategoricalArrays             0.0.4
 - CodeTools                     0.4.0
 - Codecs                        0.2.0
 - ColorTypes                    0.2.6
 - Colors                        0.6.7
 - Compat                        0.9.2
 - Compose                       0.4.4
 - Conda                         0.3.2
 - Contour                       0.2.0
 - DWARF                         0.1.0
 - DataArrays                    0.3.8
 - DataFrames                    0.8.3
 - DataStreams                   0.0.15
 - DataStructures                0.4.6
 - Distances                     0.3.2
 - Distributions                 0.10.2
 - ELF                           0.1.0
 - FileIO                        0.1.2
 - FixedPointNumbers             0.1.6
 - FixedSizeArrays               0.2.3
 - ForwardDiff                   0.2.5
 - GZip                          0.2.20
 - Gallium                       0.0.4
 - HDF5                          0.6.6
 - Hexagons                      0.0.4
 - HttpCommon                    0.2.6
 - HttpParser                    0.2.0
 - HttpServer                    0.1.6
 - Interpolations                0.3.6
 - Iterators                     0.1.10
 - JSON                          0.7.0
 - JuliaParser                   0.7.4
 - Juno                          0.2.1
 - KernelDensity                 0.3.0
 - LNR                           0.0.2
 - LaTeXStrings                  0.2.0
 - Lazy                          0.11.2
 - LegacyStrings                 0.1.1
 - Loess                         0.0.7
 - MachO                         0.0.4
 - MacroTools                    0.3.2
 - MbedTLS                       0.3.0
 - Measures                      0.0.3
 - Media                         0.2.2
 - Mustache                      0.1.2
 - Mux                           0.2.1
 - NaNMath                       0.2.1
 - NullableArrays                0.0.9
 - ObjFileBase                   0.0.4
 - Optim                         0.6.1
 - PDMats                        0.4.2
 - PositiveFactorizations        0.0.2
 - PyCall                        1.7.2
 - Ratios                        0.0.4
 - Reactive                      0.3.4
 - Reexport                      0.0.3
 - Requires                      0.3.0
 - Rmath                         0.1.3
 - SHA                           0.2.1
 - Showoff                       0.0.7
 - SortingAlgorithms             0.1.0
 - StatsBase                     0.9.0
 - StatsFuns                     0.3.1
 - StructIO                      0.0.2
 - TerminalUI                    0.0.2
 - TextWrap                      0.1.6
 - URIParser                     0.1.6
 - VT100                         0.0.2
 - WeakRefStrings                0.2.0
 - WebSockets                    0.2.1
 - WoodburyMatrices              0.2.0
```

``` bash
jamie@machine:~/imp$ apm list
Built-in Atom Packages (90)
├── about@1.5.3
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.52.0
├── atom-grammar-test@0.6.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.44.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.2
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.1
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.1
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.41.0
├── bracket-matcher@0.82.1
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.39.0
├── find-and-replace@0.201.0
├── fuzzy-finder@1.3.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.1
├── image-view@0.58.2
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── language-c@0.52.1
├── language-clojure@0.21.0
├── language-coffee-script@0.47.2
├── language-csharp@0.12.1
├── language-css@0.37.1
├── language-gfm@0.88.0
├── language-git@0.15.0
├── language-go@0.42.1
├── language-html@0.45.1
├── language-hyperlink@0.16.0
├── language-java@0.23.0
├── language-javascript@0.119.0
├── language-json@0.18.2
├── language-less@0.29.5
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.35.0
├── language-php@0.37.2
├── language-property-list@0.8.0
├── language-python@0.45.0
├── language-ruby@0.69.0
├── language-ruby-on-rails@0.25.0
├── language-sass@0.56.0
├── language-shellscript@0.22.4
├── language-source@0.9.0
├── language-sql@0.23.0
├── language-text@0.7.1
├── language-todo@0.28.0
├── language-toml@0.18.0
├── language-xml@0.34.9
├── language-yaml@0.26.0
├── line-ending-selector@0.5.0
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@0.53.1
├── notifications@0.65.0
├── one-dark-syntax@1.3.0
├── one-dark-ui@1.5.0
├── one-light-syntax@1.3.0
├── one-light-ui@1.5.0
├── open-on-github@1.2.0
├── package-generator@1.0.0
├── settings-view@0.242.2
├── snippets@1.0.2
├── solarized-dark-syntax@1.0.2
├── solarized-light-syntax@1.0.2
├── spell-check@0.67.1
├── status-bar@1.4.1
├── styleguide@0.47.0
├── symbols-view@0.113.0
├── tabs@0.100.2
├── timecop@0.33.2
├── tree-view@0.208.2
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.33.0
└── wrap-guide@0.38.1

Community Packages (10) /home/jamie/.atom/packages
├── Zen@0.16.4
├── ink@0.5.3
├── julia-client@0.5.6
├── language-julia@0.7.0
├── latex-completions@0.3.2
├── markdown-writer@2.6.1
├── project-manager@3.2.3
├── spell-check-test@0.77.5
├── tool-bar@1.0.1
└── uber-juno@0.1.1

└── (empty)
```

**Comment by jamii** [comment] 2016-09-29 11:54
Same behavior after Pkg.upgrade()

``` julia
julia> Pkg.status()
10 required packages:
 - Atom                          0.5.2
 - Benchmark                     0.1.0
 - BenchmarkTools                0.0.5
 - Blink                         0.4.1
 - Gadfly                        0.4.4
 - Hiccup                        0.0.3
 - JLD                           0.6.4
 - Match                         0.3.0
 - PyPlot                        2.2.4
 - SQLite                        0.3.7
80 additional packages:
 - ASTInterpreter                0.0.4
 - AbstractTrees                 0.0.4
 - ArgParse                      0.3.1
 - AxisAlgorithms                0.1.5
 - BinDeps                       0.4.5
 - Blosc                         0.1.7
 - COFF                          0.0.2
 - CRC                           1.1.1
 - Calculus                      0.1.15
 - CategoricalArrays             0.0.4
 - CodeTools                     0.4.1
 - Codecs                        0.2.0
 - ColorTypes                    0.2.8
 - Colors                        0.6.8
 - Compat                        0.9.2
 - Compose                       0.4.4
 - Conda                         0.3.2
 - Contour                       0.2.0
 - DWARF                         0.1.0
 - DataArrays                    0.3.8
 - DataFrames                    0.8.3
 - DataStreams                   0.0.15
 - DataStructures                0.4.6
 - Distances                     0.3.2
 - Distributions                 0.10.2
 - ELF                           0.1.0
 - FileIO                        0.1.2
 - FixedPointNumbers             0.1.8
 - FixedSizeArrays               0.2.3
 - ForwardDiff                   0.2.5
 - GZip                          0.2.20
 - Gallium                       0.0.4
 - HDF5                          0.6.6
 - Hexagons                      0.0.4
 - HttpCommon                    0.2.6
 - HttpParser                    0.2.0
 - HttpServer                    0.1.6
 - Interpolations                0.3.6
 - Iterators                     0.1.10
 - JSON                          0.7.0
 - JuliaParser                   0.7.4
 - Juno                          0.2.2
 - KernelDensity                 0.3.0
 - LNR                           0.0.2
 - LaTeXStrings                  0.2.0
 - Lazy                          0.11.2
 - LegacyStrings                 0.1.1
 - Loess                         0.0.7
 - MachO                         0.0.4
 - MacroTools                    0.3.2
 - MbedTLS                       0.3.0
 - Measures                      0.0.3
 - Media                         0.2.2
 - Mustache                      0.1.2
 - Mux                           0.2.1
 - NaNMath                       0.2.1
 - NullableArrays                0.0.9
 - ObjFileBase                   0.0.4
 - Optim                         0.6.1
 - PDMats                        0.4.2
 - PositiveFactorizations        0.0.2
 - PyCall                        1.7.2
 - Ratios                        0.0.4
 - Reactive                      0.3.4
 - Reexport                      0.0.3
 - Requires                      0.3.0
 - Rmath                         0.1.3
 - SHA                           0.2.1
 - Showoff                       0.0.7
 - SortingAlgorithms             0.1.0
 - StatsBase                     0.10.0
 - StatsFuns                     0.3.1
 - StructIO                      0.0.2
 - TerminalUI                    0.0.2
 - TextWrap                      0.1.6
 - URIParser                     0.1.6
 - VT100                         0.0.2
 - WeakRefStrings                0.2.0
 - WebSockets                    0.2.1
 - WoodburyMatrices              0.2.0
```

**Comment by MikeInnes** [comment] 2016-10-03 11:13
I think this is most likely due to us trying to display `s` and rendering the entire array as a string for the clipboard. The `gc()` is throwing me off though, is it really specific to that? Does it happen if you do `let` instead of `begin` so that `s` is hidden from the global scope?

May also be worth checking out Juno.jl, as the clipboard issue is fixed on master.

**Comment by pfitzseb** [comment] 2016-10-03 12:10
This also happens on Juno master. The problem is that we have no output limiting for strings:
```julia
"test"^100_000_000
```
will crash Atom just as reliably. The workaround with the `let`-block works though because we then don't try to render `s` in the workspace.

**Comment by MikeInnes** [comment] 2016-10-03 13:41
Ok, I've patched that on Juno master, so this issue may be fixed with that.

**Comment by pfitzseb** [comment] 2016-10-03 14:07
Yup, that works.

**Closed by pfitzseb** 2016-10-03 14:07 UTC
Labels: bug

**Comment by jamii** [comment] 2016-10-03 14:11
I'm still a little confused *why* it would be trying to render `s` when I eval `@time gc()` but not when I eval `@time begin; s = readstring(open("../imdb/movie_info.csv")); nothing; end`. (I wrapped the latter in a block specifically to avoid displaying `s`).

**Comment by jamii** [comment] 2016-10-03 14:15
It works on Juno master though, and printing big strings has been the cause of much wasted time for me, so thanks for the fix :)

**Comment by MikeInnes** [comment] 2016-10-03 14:17
The display happens because of the workspace (which we should probably disable updates on if it's not visible). Not sure why it's only happening after the second eval though; maybe there's something race-y going on where you're still transferring data for a while before crashing or something.

> so thanks for the fix :)

No problem! Happy to help however we can.

**Comment by pfitzseb** [comment] 2016-10-03 14:17
Well, we have this nifty workspace panel which will render everything in global scope. It tries to do that after you eval the `begin ... end` block and will crash Atom even without the `gc...` line after some time.

**Comment by jamii** [comment] 2016-10-03 14:21
Ah, that makes sense. I'd never opened the workspace panel. It is indeed nifty.
